# render.yaml
version: "1"
services:
  - type: web
    name: Digital-Market-Space-officiel
    runtime: node
    plan: free
    region: oregon
    buildCommand: "npm install"
    startCommand: "npm start"
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        value: "Affom@rzouck13"
      - key: PORT
        value: 10000
